---
#default vars
install: true # default true for first install
register_validator: false
update: false
username: "allora"
user_password: "super_strong_password" # use vault, check https://docs.ansible.com/ansible/2.8/user_guide/vault.html
data_dir: "/home/{{ username }}/.allora"
allora_image_version: v0.6.0
repo_url: "https://github.com/allora-network/allora-chain.git"
repo_branch: "main"
amount: "20000000uallo"
network: allora-testnet-1
allora_home: "/data"
